concise-mid-tag.cddl

Fixes ietf-rats/draft-birkholz-rats-corim#60

remove multiplicity from instance IP

---

concise-mid-tag.cddl

Add EUI-64 to the MAC address type

---

Makefile
README.md
TYPOGRAPHY.md
comid-code-points.cddl
concise-mid-tag.cddl
concise-swid-tag-ext.cddl
unsigned-corim.cddl

This only covers CoMID.  CoRIM will be done in another PR.

typographical consistency pass (part 1)

---

concise-swid-tag-ext.cddl

The text in the draft needs to be fixed accordingly.
Fixes #9

flip module-requires to requires-module, etc.

---

comid-code-points.cddl
concise-mid-tag.cddl

change comid.element-name to comid.module-name

Issue #13 fix

---

comid-code-points.cddl
concise-mid-tag.cddl

changed module-type in element-name-map to class-id and class-id-type-choice

fix for issue #15

---

concise-mid-tag.cddl

add a non-empty<> macro and use it where needed

---

.github/workflows/ci.yml
Makefile
tools.mk

does this makes sense? cabo funneled the feature into diag2diag.rb for us

this augment to Makefile will require the cbor-diag gem in the build environment

---

comid-code-points.cddl
concise-mid-tag.cddl

remove licensor and distributor

---

corim-code-points.cddl

rebase corim-entity-map codepoints

---

concise-rim.cddl

add a top-level "corim"

---

concise-mid-tag.cddl

make element name optional in the endorsement and ref-val claims

---

comid-code-points.cddl
concise-mid-tag.cddl

also add an extension socket to identity claims
Fixes #31

add optional element name to identity claims

---

comid-code-points.cddl
concise-mid-tag.cddl

Fix naming inconsistency in Instance claim map

---

concise-mid-tag.cddl

fix digests-type

---

concise-mid-tag.cddl

Use one-or-more<COSE_Key> instead of COSE_KeySet

---

concise-mid-tag.cddl

explicit endorsement values and refval values

---

Makefile
comid-triples-code-points.cddl
comid-triples.cddl
cose-key.cddl

This implements the following triples:
- 3a, 4a, 5b
NOTE: This is not built as a patch to the previous CDDL to avoid diff
madness

Restructure CDDL based on the "triples discussion"

---

concise-mid-tag.cddl

Extend SVN type to carry a min acceptable value

---

comid-code-points.cddl
concise-mid-tag.cddl

add optional (and extensible) measured-element

---

Makefile
examples/comid-1.diag
tools.mk

automatically validated samples

---

Makefile
examples/corim-unsigned-1.diag

example unsigned CoRIM

---

examples/comid-2.diag
examples/corim-unsigned-2.diag

This is a CoMID with three reference values (measurements) and one endorsement (FW version).
I wouldn't know how to add a meaningful SVN entry: @nedmsmith can you provide a suggestion?

add richer comid and (unsigned) corim

---

examples/corim-unsigned-1.diag
examples/corim-unsigned-2.diag
unsigned-corim.cddl

Add byte string wrapping around CoMID and CoSWID

---

examples/comid-2.diag

example has a RoT, firmware attesting env and two trusted OS target envs.

modified to match example in TCG spec

---

Makefile

pretty print CBOR when generating from diag

---

Makefile
concise-mid-tag.cddl
concise-rim.cddl
examples/comid-2.diag
examples/corim-unsigned-1.diag
examples/corim-unsigned-2.diag
unsigned-corim.cddl
xcorim.cddl

* CoRIM: 500-
* CoMID: 550-
Fixes #93

Renumber the CBOR tags throughout

---

concise-mid-tag.cddl

This belongs to the PSA profile
Fixes #96

remove implementationID from base

---

corim-code-points.cddl
unsigned-corim.cddl

add an optional profile attribute to the unsigned-corim-map
Fixes #99

add profile attribute

---

Makefile
concise-mid-tag.cddl
examples/comid-1.diag
examples/comid-2.diag
examples/corim-unsigned-1.diag
examples/corim-unsigned-2.diag
generic-one-or-more.cddl
signed-corim.cddl
unsigned-corim.cddl
xcorim.cddl

Drop the cute one-or-more<> optimisation

---

concise-mid-tag.cddl
examples/comid-design-cd.diag
examples/comid-firmware-cd.diag
examples/corim-design-cd.diag
examples/corim-firmware-cd.diag

make raw-value type extensible (w/ tags)

---

corim-code-points.cddl
signed-corim.cddl
unsigned-corim.cddl

add a RIM validity field to the unsigned CoRIM

---

corim-code-points.cddl
signed-corim.cddl
unsigned-corim.cddl

Split signer role from manifest creator

---

signed-corim.cddl

Make Meta an opaque field in the COSE header

---

corim-code-points.cddl
signed-corim.cddl
xcorim-code-points.cddl
xcorim.cddl

align xcorim layout with recent changes to corim

---

Makefile
concise-rim.cddl
corim-code-points.cddl
corim.cddl
examples/corim-1.diag
examples/corim-2.diag
examples/corim-design-cd.diag
examples/corim-firmware-cd.diag
signed-corim.cddl
xcorim-code-points.cddl
xcorim.cddl

Removed reference to unsigned from normal corim map

---

concise-rim.cddl
signed-corim.cddl
xcorim.cddl

adds signing of the global tag to the signature payload for corim and xcorim

Also sign the corim-map tag

---

concise-mid-tag.cddl

Add flags mask

---

examples/comid-3.diag

Add Example CoMID CBOR Diag with MKey as Int

---

signed-corim.cddl
xcorim.cddl

Switch to the new media type labels

---

media-types.md

add templates for media type registrations

---

media-types.md

add optional "profile" parameter to CoRIM media types

---

Makefile
comid-code-points.cddl
concise-mid-tag.cddl

A new encoding for the CoMID flags type
